### ISSUE TITLE
Remove the SBML L1V2 models with negative stoichiometry

### ISSUE THREAD

**Issue by hemilpanchiwala** [sbmlteam/sbml-test-suite#70]
In some of the SBML L1V2 models in the SBML Test Suite, the `speciesReference` is given a negative value for the stoichiometry. But the specification document of SBML L1V2 says that the stoichiometry for the SpeciesReference should be a positive integer.

The test cases having this issue are [1422](https://github.com/sbmlteam/sbml-test-suite/blob/develop/cases/semantic/01422/01422-sbml-l1v2.xml), [1426](https://github.com/sbmlteam/sbml-test-suite/blob/develop/cases/semantic/01426/01426-sbml-l1v2.xml), [1427](https://github.com/sbmlteam/sbml-test-suite/blob/develop/cases/semantic/01427/01427-sbml-l1v2.xml), and [1432](https://github.com/sbmlteam/sbml-test-suite/blob/develop/cases/semantic/01432/01432-sbml-l1v2.xml) in the develop branch. The L1V2 models for these test cases should be removed from the test suite as they are not valid cases.

Here is the snapshot from the SBML specification:
<img width="699" alt="Bildschirmfoto 2020-07-01 um 20 04 25" src="https://user-images.githubusercontent.com/42446679/86319494-46d62180-bc52-11ea-8b8e-a78c7c2d0a87.png">

**Comment by luciansmith** [comment]
Thank you for finding this!  This is now fixed with https://github.com/sbmlteam/sbml-test-suite/commit/102ccace400a374dbe2abe9291da959f8172ad2d  

As it turned out, the l1v2 version of 1433 also needed to be dropped.

We're also entering this as a bug in libsbml, so that it will catch the fact that these models are not valid.
