### ISSUE TITLE
tests with compartment volume assignments

### ISSUE THREAD

**Issue by FFroehlich** [sbmlteam/sbml-test-suite#90]
Thanks to https://github.com/AMICI-dev/AMICI/issues/2062 we just realised there are a couple of edge cases with volume assignment rules that we did not handle adequately in AMICI. As we are passing all test cases that do not contain any features that we explicitly do not support (we do not support a subset of compartment assignments via events), we have reason to believe the test-suite currently does not sufficiently cover concentration changes due to volume changes.

**Comment by luciansmith** [comment]
You closed this--if I'm reading the issue correctly, the problem is not the SBML file itself, but re-setting the initial conditions of a model after the SBML is read?  And thus wouldn't be covered by the SBML test suite?

It could be covered by a SED-ML test suite with some ModelChanges, I think; I'll keep that in mind if we get to create such a beast.

**Comment by FFroehlich** [comment]
> You closed this--if I'm reading the issue correctly, the problem is not the SBML file itself, but re-setting the initial conditions of a model after the SBML is read? And thus wouldn't be covered by the SBML test suite?

Yes, that's correct. It's still relevant for systems where compartments (and potentially also species) are assigned via events, but there likely already are tests for that already and we simply currently don't support those events.

**Comment by luciansmith** [comment]
Thanks!
